FTS

diff --git a/.github/workflows/ansible-lint.yaml b/.github/workflows/ansible-lint.yaml
--- a/.github/workflows/ansible-lint.yaml
+++ b/.github/workflows/ansible-lint.yaml
@@ -9,9 +9,32 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - name: Run ansible-lint
-        uses: ansible/ansible-lint@main
-        with:
-          args: "-v"
-          python_dependency_file: requirements.txt
-          requirements_file: collections/requirements.yaml
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        python-version: "3.12"
+      - name: Setup and Run ansible-lint
+        shell: bash
+        run: |
+          TMP_DIRECTORY=/tmp
+
+          if [ ! -z "${GITHUB_ACTIONS}" ]; then
+            TMP_DIRECTORY=$RUNNER_TEMP
+          fi
+
+          python -m venv $TMP_DIRECTORY/temp-venv
+          . $TMP_DIRECTORY/temp-venv/bin/activate
+
+          if [ -z "${VIRTUAL_ENV}" ]; then
+            echo "Could not determine if we are running in a virtual environment...bailing."
+            exit 1
+          fi
+
+          pip install -U -r requirements.txt
+
+          # ansible-galaxy collection install -r collections/requirements.yaml
+
+          ansible-lint -f full --profile production -v
+
+          if [ -z "${GITHUB_ACTIONS}"]; then
+            rm -rf /tmp/temp-venv
+          fi
